"""
Django settings for project2 project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


ALLOWED_HOSTS = []



# إعدادات الوسائط الاجتماعية
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]




SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
}




# Application definition

INSTALLED_APPS = [
    'crispy_forms',
    'crispy_bootstrap4',
    'rest_framework',
    'products.apps.ProductsConfig',
    'orders.apps.OrdersConfig',
    'cart.apps.CartConfig',
    'accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'social_auth',
    'django_extensions',
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

SITE_ID = 1


# إعدادات Google
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID' , default='')
GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET' , default='')
GOOGLE_REDIRECT_URI = 'http://localhost:8000/social-auth/google/callback/'



DEBUG = config('DEBUG', default=True , cast=bool)

SECRET_KEY = config('SECRET_KEY', default='django-insecure-development-key')

AUTH_USER_MODEL = 'accounts.CustomUser'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR , 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'project2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR , 'static')
STATICFILES_DIRS = [os .path.join(BASE_DIR , 'project2/static')]


# MEDIA 
MEDIA_ROOT = os.path.join(BASE_DIR  , 'media')
MEDIA_URL = '/media/'


# BootStrap
CRISPY_TEMPLATE_PACK = 'bootstrap4'



# إعدادات التوجيه
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'




# إعدادات إضافية موصى بها
ACCOUNT_SESSION_REMEMBER = True  # تذكر حالة تسجيل الدخول
ACCOUNT_PRESERVE_USERNAME_CASING = False  # تجاهل حالة الأحرف في الأسماء
ACCOUNT_UNIQUE_EMAIL = True  # التأكد من أن البريد الإلكتروني فريد
ACCOUNT_MAX_EMAIL_ADDRESSES = 1  # حد عناوين البريد الإلكتروني لكل حساب


# إعدادات الأمان
ACCOUNT_RATE_LIMITS =  {
    # الحد من محاولات تسجيل الدخول الفاشلة
    'login_failed': {
        'method': 'POST',
        'rate': '5/m',  # 5 محاولات في الدقيقة
    },
    
    # الحد من محاولات تسجيل الدخول الناجحة
    'login': {
        'method': 'POST', 
        'rate': '10/m',  # 10 محاولات في الدقيقة
    },
    
    # الحد من محاولات التسجيل
    'signup': {
        'method': 'POST',
        'rate': '20/m',  #  20 محاولات في الدقيقة
    },
}
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3



# Email 
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # أو مزود البريد الإلكتروني الخاص بك
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'haedaralsuleman64@gmail.com'  # استبدل ببريدك الإلكتروني
EMAIL_HOST_PASSWORD = ''  # استبدل بكلمة مرور التطبيق

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
