# Generated by Django 5.2.5 on 2025-09-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('On hold', 'On hold'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delevered', 'Delevered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10, verbose_name='status order'),
        ),
    ]
