# Generated by Django 5.2.5 on 2025-09-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'verbose_name': 'حساب اجتماعي', 'verbose_name_plural': 'الحسابات الاجتماعية'},
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider_id',
            field=models.CharField(max_length=255),
        ),
    ]
