# Generated by Django 5.2.5 on 2025-09-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_auth', '0002_alter_socialaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'verbose_name': 'Social account', 'verbose_name_plural': 'Social accounts'},
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google')], max_length=20),
        ),
    ]
