# Generated by Django 5.2.5 on 2025-08-31 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='title category')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='link')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='name in arabic')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name in english')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%d', verbose_name='category photo')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categorys',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='title product')),
                ('slug', models.SlugField(max_length=200, verbose_name='link')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created in ')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('image', models.ImageField(blank=True, upload_to='photos/%y/%m/%d', verbose_name='photo')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تم الموافقة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['id', 'slug'], name='products_pr_id_a08e3c_idx')],
            },
        ),
    ]
